### PR TITLE
style: 💄 Fix page layout and alignment

### LINKED ISSUE #21: Fix page layout and alignment
https://www.learnui.design/blog/3-pro-tips-on-alignment.html
https://www.learnui.design/blog/why-beginning-designers-dont-need-grids-type-scales-color-theory.html

### PR DESCRIPTION
**Pull request by ianjmacintosh**
Getting closer to looking good!

### CODE REVIEW

File: src/App.jsx [hunk 1]
```diff
@@ -37,71 +37,67 @@ function App() {
...
-            <label className="block text-base uppercase font-bold text-gray-700 mb-2">
-              QR Code
-            </label>
+          <label className="block text-base uppercase font-bold text-gray-700 mb-2">
+            QR Code
+          </label>
 
-            <div className="flex justify-center border rounded-md border-gray-200 bg-white text-sm text-gray-700 shadow-sm mb-2">
+          <div className="space-y-6">
+            <div className="border border-gray-300 rounded-md bg-white w-full flex flex-col items-center ">
```
Comment (ianjmacintosh) [inline src/App.jsx:94]: Huh. Trailing whitespace is permitted in values?
